### ISSUE TITLE
Hashing not implemented correctly

### ISSUE THREAD

**Issue by DivineTraube** [MagnusS/Java-BloomFilter#3]
Your hash implementation has a problem. What you do is:
1. Generate a hash, for instance 128bit MD5 hash.
2. Split the hash in 4 byte chunks and interpret them a pseudorandom integers.
3. When a value is inserted in the bloomfilter: take each random int and do a modulo w.r.t. the size of the bloom filter

The last part is wrong/dangerous since it violates the assumption that hash values are evenly distributed over [1,m) with m being the size of the bloom filter. Here is why:
Suppose the bloom filter has a size of 3 billion. The hash value are integers so approximately uniformly distributed from 0 to roughly 4 billion. By taking the modulo the hash values between 0 and 1 billion get generated twice as often as the range 1 billion to 3 billion, as the range 3 billion to 4 billion is mapped to 0 - 1 billion. You should easily be able to verify that by taking a histogram of a large number of hashes.

This corruption of uniformity will lead to a decreased false positive rate and hence should be fixed (for instance by discarding the values which are two high instead of taking the modulo).

**Comment by DivineTraube** [comment]
I did a Chi-Squared Goodness of Fit Test to test my hashes and also applied it to yours - the hashvalues aren't evenly distributed (m=100, 40 000 hash calculations):

Histogram for Hashvalues:
Index 0: 429, Deviation from expectation: 7.25E-4
Index 1: 781, Deviation from expectation: 0.009525
Index 2: 273, Deviation from expectation: 0.003175
Index 3: 351, Deviation from expectation: 0.0012250000000000004
Index 4: 627, Deviation from expectation: 0.005675000000000001
Index 5: 508, Deviation from expectation: 0.0026999999999999993
Index 6: 549, Deviation from expectation: 0.003724999999999999
Index 7: 313, Deviation from expectation: 0.002175
Index 8: 273, Deviation from expectation: 0.003175
Index 9: 430, Deviation from expectation: 7.499999999999989E-4
Index 10: 430, Deviation from expectation: 7.499999999999989E-4
Index 11: 273, Deviation from expectation: 0.003175
Index 12: 390, Deviation from expectation: 2.500000000000002E-4
Index 13: 195, Deviation from expectation: 0.005125
Index 14: 312, Deviation from expectation: 0.0022000000000000006
Index 15: 431, Deviation from expectation: 7.749999999999996E-4
Index 16: 468, Deviation from expectation: 0.0017000000000000001
Index 17: 312, Deviation from expectation: 0.0022000000000000006
Index 18: 468, Deviation from expectation: 0.0017000000000000001
Index 19: 352, Deviation from expectation: 0.0011999999999999997
Index 20: 469, Deviation from expectation: 0.001724999999999999
Index 21: 468, Deviation from expectation: 0.0017000000000000001
Index 22: 390, Deviation from expectation: 2.500000000000002E-4
Index 23: 507, Deviation from expectation: 0.0026750000000000003
Index 24: 509, Deviation from expectation: 0.002725
Index 25: 117, Deviation from expectation: 0.007075
Index 26: 312, Deviation from expectation: 0.0022000000000000006
Index 27: 351, Deviation from expectation: 0.0012250000000000004
Index 28: 352, Deviation from expectation: 0.0011999999999999997
Index 29: 469, Deviation from expectation: 0.001724999999999999
Index 30: 313, Deviation from expectation: 0.002175
Index 31: 351, Deviation from expectation: 0.0012250000000000004
Index 32: 235, Deviation from expectation: 0.004125
Index 33: 351, Deviation from expectation: 0.0012250000000000004
Index 34: 469, Deviation from expectation: 0.001724999999999999
Index 35: 509, Deviation from expectation: 0.002725
Index 36: 586, Deviation from expectation: 0.00465
Index 37: 313, Deviation from expectation: 0.002175
Index 38: 430, Deviation from expectation: 7.499999999999989E-4
Index 39: 234, Deviation from expectation: 0.00415
Index 40: 235, Deviation from expectation: 0.004125
Index 41: 703, Deviation from expectation: 0.007575
Index 42: 313, Deviation from expectation: 0.002175
Index 43: 586, Deviation from expectation: 0.00465
Index 44: 195, Deviation from expectation: 0.005125
Index 45: 273, Deviation from expectation: 0.003175
Index 46: 312, Deviation from expectation: 0.0022000000000000006
Index 47: 546, Deviation from expectation: 0.0036500000000000005
Index 48: 273, Deviation from expectation: 0.003175
Index 49: 470, Deviation from expectation: 0.0017499999999999998
Index 50: 390, Deviation from expectation: 2.500000000000002E-4
Index 51: 351, Deviation from expectation: 0.0012250000000000004
Index 52: 430, Deviation from expectation: 7.499999999999989E-4
Index 53: 470, Deviation from expectation: 0.0017499999999999998
Index 54: 353, Deviation from expectation: 0.0011750000000000007
Index 55: 390, Deviation from expectation: 2.500000000000002E-4
Index 56: 625, Deviation from expectation: 0.005625
Index 57: 274, Deviation from expectation: 0.00315
Index 58: 390, Deviation from expectation: 2.500000000000002E-4
Index 59: 196, Deviation from expectation: 0.0051
Index 60: 507, Deviation from expectation: 0.0026750000000000003
Index 61: 390, Deviation from expectation: 2.500000000000002E-4
Index 62: 471, Deviation from expectation: 0.0017750000000000005
Index 63: 351, Deviation from expectation: 0.0012250000000000004
Index 64: 313, Deviation from expectation: 0.002175
Index 65: 195, Deviation from expectation: 0.005125
Index 66: 429, Deviation from expectation: 7.25E-4
Index 67: 430, Deviation from expectation: 7.499999999999989E-4
Index 68: 390, Deviation from expectation: 2.500000000000002E-4
Index 69: 390, Deviation from expectation: 2.500000000000002E-4
Index 70: 351, Deviation from expectation: 0.0012250000000000004
Index 71: 351, Deviation from expectation: 0.0012250000000000004
Index 72: 313, Deviation from expectation: 0.002175
Index 73: 351, Deviation from expectation: 0.0012250000000000004
Index 74: 351, Deviation from expectation: 0.0012250000000000004
Index 75: 429, Deviation from expectation: 7.25E-4
Index 76: 587, Deviation from expectation: 0.004675
Index 77: 351, Deviation from expectation: 0.0012250000000000004
Index 78: 390, Deviation from expectation: 2.500000000000002E-4
Index 79: 469, Deviation from expectation: 0.001724999999999999
Index 80: 430, Deviation from expectation: 7.499999999999989E-4
Index 81: 352, Deviation from expectation: 0.0011999999999999997
Index 82: 510, Deviation from expectation: 0.002749999999999999
Index 83: 274, Deviation from expectation: 0.00315
Index 84: 195, Deviation from expectation: 0.005125
Index 85: 390, Deviation from expectation: 2.500000000000002E-4
Index 86: 273, Deviation from expectation: 0.003175
Index 87: 509, Deviation from expectation: 0.002725
Index 88: 429, Deviation from expectation: 7.25E-4
Index 89: 468, Deviation from expectation: 0.0017000000000000001
Index 90: 624, Deviation from expectation: 0.005599999999999999
Index 91: 312, Deviation from expectation: 0.0022000000000000006
Index 92: 469, Deviation from expectation: 0.001724999999999999
Index 93: 158, Deviation from expectation: 0.00605
Index 94: 391, Deviation from expectation: 2.249999999999995E-4
Index 95: 702, Deviation from expectation: 0.007549999999999999
Index 96: 508, Deviation from expectation: 0.0026999999999999993
Index 97: 585, Deviation from expectation: 0.004625000000000001
Index 98: 507, Deviation from expectation: 0.0026750000000000003
Index 99: 430, Deviation from expectation: 7.499999999999989E-4
Histogram for Pseudorandom Numbers:
Index 0: 403, Deviation from expectation: 7.500000000000041E-5
Index 1: 388, Deviation from expectation: 2.999999999999999E-4
Index 2: 427, Deviation from expectation: 6.750000000000003E-4
Index 3: 401, Deviation from expectation: 2.499999999999898E-5
Index 4: 399, Deviation from expectation: 2.5000000000000716E-5
Index 5: 409, Deviation from expectation: 2.249999999999995E-4
Index 6: 403, Deviation from expectation: 7.500000000000041E-5
Index 7: 393, Deviation from expectation: 1.749999999999998E-4
Index 8: 383, Deviation from expectation: 4.2500000000000003E-4
Index 9: 413, Deviation from expectation: 3.2500000000000064E-4
Index 10: 372, Deviation from expectation: 7.00000000000001E-4
Index 11: 399, Deviation from expectation: 2.5000000000000716E-5
Index 12: 396, Deviation from expectation: 9.99999999999994E-5
Index 13: 411, Deviation from expectation: 2.749999999999992E-4
Index 14: 404, Deviation from expectation: 9.99999999999994E-5
Index 15: 422, Deviation from expectation: 5.500000000000001E-4
Index 16: 358, Deviation from expectation: 0.0010500000000000006
Index 17: 369, Deviation from expectation: 7.749999999999996E-4
Index 18: 373, Deviation from expectation: 6.750000000000003E-4
Index 19: 417, Deviation from expectation: 4.2500000000000003E-4
Index 20: 389, Deviation from expectation: 2.7500000000000094E-4
Index 21: 408, Deviation from expectation: 2.0000000000000052E-4
Index 22: 404, Deviation from expectation: 9.99999999999994E-5
Index 23: 394, Deviation from expectation: 1.5000000000000083E-4
Index 24: 430, Deviation from expectation: 7.499999999999989E-4
Index 25: 434, Deviation from expectation: 8.500000000000001E-4
Index 26: 416, Deviation from expectation: 3.999999999999993E-4
Index 27: 408, Deviation from expectation: 2.0000000000000052E-4
Index 28: 414, Deviation from expectation: 3.499999999999996E-4
Index 29: 393, Deviation from expectation: 1.749999999999998E-4
Index 30: 418, Deviation from expectation: 4.49999999999999E-4
Index 31: 426, Deviation from expectation: 6.499999999999995E-4
Index 32: 401, Deviation from expectation: 2.499999999999898E-5
Index 33: 407, Deviation from expectation: 1.749999999999998E-4
Index 34: 364, Deviation from expectation: 8.999999999999998E-4
Index 35: 380, Deviation from expectation: 5.000000000000004E-4
Index 36: 419, Deviation from expectation: 4.7499999999999973E-4
Index 37: 427, Deviation from expectation: 6.750000000000003E-4
Index 38: 434, Deviation from expectation: 8.500000000000001E-4
Index 39: 378, Deviation from expectation: 5.500000000000001E-4
Index 40: 405, Deviation from expectation: 1.250000000000001E-4
Index 41: 381, Deviation from expectation: 4.7499999999999973E-4
Index 42: 444, Deviation from expectation: 0.0011000000000000003
Index 43: 388, Deviation from expectation: 2.999999999999999E-4
Index 44: 391, Deviation from expectation: 2.249999999999995E-4
Index 45: 402, Deviation from expectation: 4.99999999999997E-5
Index 46: 413, Deviation from expectation: 3.2500000000000064E-4
Index 47: 393, Deviation from expectation: 1.749999999999998E-4
Index 48: 391, Deviation from expectation: 2.249999999999995E-4
Index 49: 389, Deviation from expectation: 2.7500000000000094E-4
Index 50: 393, Deviation from expectation: 1.749999999999998E-4
Index 51: 427, Deviation from expectation: 6.750000000000003E-4
Index 52: 430, Deviation from expectation: 7.499999999999989E-4
Index 53: 404, Deviation from expectation: 9.99999999999994E-5
Index 54: 388, Deviation from expectation: 2.999999999999999E-4
Index 55: 410, Deviation from expectation: 2.500000000000002E-4
Index 56: 400, Deviation from expectation: 0.0
Index 57: 394, Deviation from expectation: 1.5000000000000083E-4
Index 58: 424, Deviation from expectation: 5.999999999999998E-4
Index 59: 393, Deviation from expectation: 1.749999999999998E-4
Index 60: 403, Deviation from expectation: 7.500000000000041E-5
Index 61: 386, Deviation from expectation: 3.499999999999996E-4
Index 62: 383, Deviation from expectation: 4.2500000000000003E-4
Index 63: 396, Deviation from expectation: 9.99999999999994E-5
Index 64: 373, Deviation from expectation: 6.750000000000003E-4
Index 65: 413, Deviation from expectation: 3.2500000000000064E-4
Index 66: 398, Deviation from expectation: 4.99999999999997E-5
Index 67: 398, Deviation from expectation: 4.99999999999997E-5
Index 68: 419, Deviation from expectation: 4.7499999999999973E-4
Index 69: 409, Deviation from expectation: 2.249999999999995E-4
Index 70: 369, Deviation from expectation: 7.749999999999996E-4
Index 71: 422, Deviation from expectation: 5.500000000000001E-4
Index 72: 382, Deviation from expectation: 4.5000000000000075E-4
Index 73: 409, Deviation from expectation: 2.249999999999995E-4
Index 74: 417, Deviation from expectation: 4.2500000000000003E-4
Index 75: 370, Deviation from expectation: 7.500000000000007E-4
Index 76: 371, Deviation from expectation: 7.25E-4
Index 77: 395, Deviation from expectation: 1.250000000000001E-4
Index 78: 409, Deviation from expectation: 2.249999999999995E-4
Index 79: 364, Deviation from expectation: 8.999999999999998E-4
Index 80: 383, Deviation from expectation: 4.2500000000000003E-4
Index 81: 390, Deviation from expectation: 2.500000000000002E-4
Index 82: 418, Deviation from expectation: 4.49999999999999E-4
Index 83: 395, Deviation from expectation: 1.250000000000001E-4
Index 84: 421, Deviation from expectation: 5.249999999999994E-4
Index 85: 413, Deviation from expectation: 3.2500000000000064E-4
Index 86: 372, Deviation from expectation: 7.00000000000001E-4
Index 87: 423, Deviation from expectation: 5.749999999999991E-4
Index 88: 428, Deviation from expectation: 6.999999999999992E-4
Index 89: 357, Deviation from expectation: 0.0010749999999999996
Index 90: 378, Deviation from expectation: 5.500000000000001E-4
Index 91: 411, Deviation from expectation: 2.749999999999992E-4
Index 92: 410, Deviation from expectation: 2.500000000000002E-4
Index 93: 407, Deviation from expectation: 1.749999999999998E-4
Index 94: 342, Deviation from expectation: 0.00145
Index 95: 416, Deviation from expectation: 3.999999999999993E-4
Index 96: 411, Deviation from expectation: 2.749999999999992E-4
Index 97: 387, Deviation from expectation: 3.2500000000000064E-4
Index 98: 391, Deviation from expectation: 2.249999999999995E-4
Index 99: 417, Deviation from expectation: 4.2500000000000003E-4
Reject that hash-values are uniformly disitributed, with significance level alpha=0.01: true
For random numbers: false
P-Value of the Chi-Squared-Test: 0.0
For random numbers: 0.5938042904512024
Chi-Squared-statistic: 3788.100000000001
For random numbers: 95.04499999999997

**Comment by MagnusS** [comment]
The hash results used in the implementation are not truly random, but are expected to be good enough for most use cases. You could probably improve the randomness by adding more hash functions, but this is at the cost of speed. You can also change MD5 to SHA1 and see if this improves your results. If you have a suggestion (or a patch) that improves the randomness I'd be happy to consider it.

Regarding the modulo issue, the effect of this is minimal when the length (m) is many times smaller than 4 billion, which I expect it to be in most cases. If you need a Bloom filter that can handle 1 billion data entries, you should probably change the implementation to use larger hash values (e.g. 64 bit).
